name: Test Suite Tricount

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: make install

    - name: run tests
      run: make test

